# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20160419_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='Distance',
        ),
    ]
